This notebook will serve as a example of how algorithm intelligence helps solving problems. 
We will take the simple example of the Sudoku and try to solve it using different techniques, from the simplest to the more advance ones. 

***backtracking***

***graph coloring***

***integer programming***

***reinforcement learning***

## creating a sudoku grid
First of all we need to create sudoku grid in a efficient and smart way: it will be a two-dimensional array. Then, for each method, a transformation will be made to fit to the current method. 



In [1]:
import numpy as np
from tqdm import tqdm
from matplotlib import pyplot as plt

In [2]:
from sudoku import Sudoku

In [3]:
test1 = Sudoku()

In [4]:
print(test1.grid)

[[0. 4. 0. 0. 0. 0. 0. 6. 0.]
 [7. 0. 0. 8. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 1. 0. 0. 0. 3.]
 [3. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 4. 0. 0. 0. 6. 0. 0.]
 [0. 6. 0. 0. 0. 0. 0. 1. 8.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 3. 0. 0. 8. 0. 0. 5.]]


In [ ]:
counts = {}
for j in range(10,20):
    count = 0
    N_test = 100
    for i in range(N_test):
        test = Sudoku(n = j)
        count += test.count
    count /= N_test
    counts[j] = count

In [ ]:
counts

## Backtracking
We will use backtracking to try to complete the Sudoku grid. At each new cell, we will try the first digit that can be added there and move to the next one and try to do the same for the next cell. If there is an issue, we backtrack and set a superior number in that cell.

In [25]:
test_backtrack = Sudoku()
result_backtrack = test_backtrack.complete_sudoku()

In [26]:
print(result_backtrack)

True


In [27]:
if result_backtrack == True:
    print(test_backtrack._solution)
    print(test_backtrack._time)

[[1. 3. 7. 8. 2. 9. 5. 6. 4.]
 [4. 5. 8. 7. 6. 3. 9. 1. 2.]
 [2. 9. 6. 1. 4. 5. 3. 7. 8.]
 [3. 1. 4. 9. 5. 6. 8. 2. 7.]
 [8. 7. 9. 2. 1. 4. 6. 3. 5.]
 [6. 2. 5. 3. 8. 7. 4. 9. 1.]
 [5. 6. 3. 4. 7. 1. 2. 8. 9.]
 [7. 4. 2. 6. 9. 8. 1. 5. 3.]
 [9. 8. 1. 5. 3. 2. 7. 4. 6.]]
0.5275743007659912


In [ ]:
times = []
for i in tqdm(range(1000)):
    test = Sudoku()
    result = test.complete_sudoku()
    if result == True:
        times.append(test._time)

In [ ]:
times

## Integer programming

In this section, I will use the pulp package. It is a linear/integer programming python package. 

In [8]:
test_IP = Sudoku()
result_IP = test_IP.complete_sudoku(method = "IP")


In [9]:
print(result_IP)

True


In [10]:
if result_IP == True:
    print(test_IP._solution)
    print(test_IP._time)

[[3. 2. 5. 7. 8. 9. 4. 1. 6.]
 [9. 4. 8. 6. 2. 1. 3. 7. 5.]
 [1. 6. 7. 5. 4. 3. 8. 2. 9.]
 [8. 9. 3. 2. 6. 7. 5. 4. 1.]
 [6. 1. 4. 8. 9. 5. 2. 3. 7.]
 [7. 5. 2. 1. 3. 4. 6. 9. 8.]
 [2. 7. 1. 3. 5. 6. 9. 8. 4.]
 [5. 8. 9. 4. 1. 2. 7. 6. 3.]
 [4. 3. 6. 9. 7. 8. 1. 5. 2.]]
0.05309152603149414


In [11]:
times = []
for i in tqdm(range(1000)):
    test = Sudoku()
    result = test.complete_sudoku(method = "IP")
    if result == True:
        times.append(test._time)

100%|██████████| 1000/1000 [03:18<00:00,  5.95it/s]


In [ ]:
plt.hist(times, bins=20)
plt.show()

In [ ]:
print("mean: " + str(np.mean(times)))
print("standard deviation: " + str(np.std(times)))
print("min: " + str(np.min(times)))
print("max: " + str(np.max(times)))

## Reinforcement learning

In this section, I will use reinforcement learning to learn how to solve a Sudoku in a human fashion.

In [ ]:
import gym

In [ ]:
print(gym.__version__)

In [ ]:
from gym.envs.registration import register

In [ ]:
register