This notebook will serve as a example of how algorithm intelligence helps solving problems. 
We will take the simple example of the Sudoku and try to solve it using different techniques, from the simplest to the more advance ones. 

***backtracking***

***graph coloring***

***integer programming***

***reinforcement learning***

## creating a sudoku grid
First of all we need to create sudoku grid in a efficient and smart way: it will be a two-dimensional array. Then, for each method, a transformation will be made to fit to the current method. 



In [1]:
import numpy as np
from tqdm import tqdm

In [2]:
from sudoku import Sudoku

In [3]:
test1 = Sudoku()

In [4]:
print(test1.grid)

[[7. 2. 0. 0. 4. 0. 0. 0. 1.]
 [5. 4. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 4. 2. 0. 0. 7. 0.]
 [4. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 0. 0. 0. 0.]
 [0. 0. 3. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 3.]
 [0. 0. 0. 0. 0. 6. 0. 0. 8.]]


In [5]:
counts = {}
for j in range(10,20):
    count = 0
    N_test = 100
    for i in range(N_test):
        test = Sudoku(n = j)
        count += test.count
    count /= N_test
    counts[j] = count

In [6]:
counts

{10: 4.03,
 11: 6.68,
 12: 10.26,
 13: 13.81,
 14: 21.77,
 15: 34.02,
 16: 64.55,
 17: 123.81,
 18: 245.45,
 19: 374.14}

## Backtracking
We will use backtracking to try to complete the Sudoku grid. At each new cell, we will try the first digit that can be added there and move to the next one and try to do the same for the next cell. If there is an issue, we backtrack and set a superior number in that cell.

We will use a stack to perform this. 

## Integer programming

In this section, I will use the pulp package. It is a linear/integer programming python package. 

In [10]:
test_IP = Sudoku()
result_IP = test_IP.complete_sudoku(method = "IP")


In [11]:
print(result_IP)

True


In [14]:
if result_IP == True:
    print(test_IP._solution)

[[8. 3. 9. 4. 5. 2. 1. 6. 7.]
 [5. 7. 2. 3. 6. 1. 4. 8. 9.]
 [1. 4. 6. 9. 7. 8. 5. 2. 3.]
 [9. 5. 8. 1. 2. 7. 6. 3. 4.]
 [7. 2. 4. 8. 3. 6. 9. 1. 5.]
 [6. 1. 3. 5. 4. 9. 2. 7. 8.]
 [2. 8. 1. 7. 9. 5. 3. 4. 6.]
 [3. 9. 7. 6. 1. 4. 8. 5. 2.]
 [4. 6. 5. 2. 8. 3. 7. 9. 1.]]


In [13]:
test_IP.grid

array([[0., 3., 0., 4., 5., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 2., 0.],
       [0., 0., 8., 1., 0., 0., 0., 0., 0.],
       [0., 2., 4., 0., 0., 6., 0., 0., 5.],
       [0., 0., 0., 0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 7., 0., 0., 0., 8., 5., 2.],
       [0., 6., 0., 2., 0., 3., 0., 0., 0.]])

## Reinforcement learning

In this section, I will use reinforcement learning to learn how to solve a Sudoku in a human fashion.